spring.application.name=HotelBookingApplication
jwt.secret=HkG9Q3j2vWl8U6mN9zX7aErT4bYqZs1pHvKdFtJuLwMxCgTnJrOyBpEsTzXwYvZq
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://172.29.3.5:5678/db_telecash_dev?currentSchema=testcase
spring.datasource.username=user_telecash_stage
spring.datasource.password=tvh@1m^jTm67Iw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080